spring:
  application:
    name: AgentAthreya-ConversationService
  # profiles:
  #   active: docker
  
  datasource:
    url: jdbc:postgresql://localhost:5432/agentathreya
    username: naveen
    password: naveen123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    com:
      agentathreya: DEBUG

jwt:
  secret: GR8Zt4X6hnt5XBgAZd1svN0BL_fCJSraZ8DEXnuE9Wo
  expiration: 360000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

llm:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${OPENAI_API_KEY}