spring:
  application:
    name: AgentAthreya-ConversationService
  # profiles:
  #   active: docker

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    com:
      agentathreya: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

llm:
  api:
    url: ${LLM_API_URL}
    key: ${OPENAI_API_KEY}
server:
  port: 8081
